name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v1
       
       - name: Set up JDK 17
         uses: actions/setup-java@v1
         with:
           java-version: 17
           
       - name: Maven Build
         run: mvn -B clean package -DskipTests
         
       - name: Run unit tests
         run: mvn -B test
         
       - name: Collect artifacts
         uses: actions/upload-artifact@v2
         with:
            name: Packaged-Artifacts
            path: target/*.jar